### ISSUE TITLE
Can't get gis files in PRMS legacy notebook example

### ISSUE THREAD

**Issue by jdickins-usgs** [EC-USGS/pywatershed#218]
Should these files be in the develop distribution? Can't find them.
ImportError: cannot import name 'gis_files' from 'helpers' (C:\Users\jdickins\AppData\Local\mambaforge\envs\pywatershed\lib\site-packages\helpers\__init__.py)

**Comment by jmccreight** [comment]
Thanks. There are no files in the repo, `gis_files` is a module that downloads/manages these files.
This error/effect I cant reproduce yet. 
I'm assuming the cause is 

1. Windows
2. development install (pip install -e .) 
3. this is the 2nd cell in a notebook of one of the notebooks 00-02, so it is running in Jupyter. 

Let me know if any of that is wrong.

**Comment by jmccreight** [comment]
To be clear the `ImportError` was because `helpers.gis_files` is only available in the `examples/` directory, it is not part of general pywatershed functionality/modules. It just checks for gis files that support plotting in the examples and if they are not available locally, it downloads gis files in the artifacts of the first pywatershed release.
